### ISSUE TITLE
View policies for users tagged under 'management' and 'monitoring' roles

### ISSUE THREAD

**Issue by epretha** [rabbitmq/rabbitmq-management#156]
As of March 2016, policies are visible (and also create, update and delete) only for those users who are tagged under the 'policymaker' and 'administrator' roles. Please consider the 'management' and 'monitoring' roles to allow viewing policies but not updating/deleting them.

**Comment by uvzubovs** [comment]
+1

This is a big usability gap. In our environment developers do not have policymaker role because we restrict queue sizes and HA settings enterprise-wide. As a result, developers cannot even see what's implied by the policy, which degrades self-service.

**Comment by uvzubovs** [comment]
Please be careful and not expose upstreams because URIs contain federation user password.

**Comment by michaelklishin** [comment]
@hairyhum yeah, maybe we should undo the parameters part.

**Comment by hairyhum** [comment]
Monitoring user still can see active federation links and shovels. Maybe it makes sense to keep access to parameters for monitoring user?

**Comment by uvzubovs** [comment]
As I mentioned, upstream configuration includes the URI, which may include the password used by the federation plug-in to connect to the upstream. Either the password needs to be scrubbed or administrator tag should be required to view upstream configuration. 

We did not encounter a need to view upstream configuration by monitor because federation link object contains the URL field, which is the URI minus the credentials.

**Comment by hairyhum** [comment]
Reverted access to parameters.

**Comment by michaelklishin** [comment]
Thank you, @hairyhum. @uvzubovs we are going to release another milestone of `3.6.2` so you can try the solution we have so far.
