### ISSUE TITLE
Create separate dropdown panels for delete and purge options

### ISSUE THREAD

**Issue by bdshroyer** [rabbitmq/rabbitmq-management#158]
During design feedback on [PR #147](https://github.com/rabbitmq/rabbitmq-management/pull/147), one of the designers suggested that we put the Delete and Purge buttons in separate dropdowns. Doing this might a) give us the chance to further differentiate between the two, and b) cut down on the chance of accidentally deleting queues.

**Comment by zbentley** [comment]
I think that this is probably unnecessary. If anything, the delete/purge buttons should be featured more prominently on the main pane; the confirmation dialog should be sufficient to prevent accidental deletions (if people are going to confirm a dialog by accident, they're probably going to open a section and confirm a dialog by accident as well).

If additional confirmations are added (e.g. for purge in #195), I think it would be very useful for the buttons on the confirmations to indicate the action being confirmed. Instead of "OK", it would be "Delete Queue" or "Purge Queue". I'm about as far from frontend development as can be, though: that may not be possible.
