### ISSUE TITLE
Socket used counter is inaccurate in management UI

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#193]
This might be an issue in the core but filing it here for now.

I'm running the test suite of [rabbit-hole](https://github.com/michaelklishin/rabbit-hole) for 2K times and memory is holding steady. I have, however, noticed that on run ~ 900 I have used sockets reported as 800+ in the UI but only

```
 {file_descriptors,
     [{total_limit,924},{total_used,3},{sockets_limit,829},{sockets_used,2}]},
```

in `rabbitmqctl status`. The difference is significant enough to look suspicious.

**Comment by dcorbacho** [comment]
The fix for the socket count introduced in 3.6.0 https://github.com/rabbitmq/rabbitmq-management/commit/6c44e9cd8c08d33caf0e721d8bff0eb1148c7f0c got lost in the refactor https://github.com/rabbitmq/rabbitmq-management/commit/0bbe33677a559670ffb6f95f0203c26f01fab75c. 

Fixed (again) in https://github.com/rabbitmq/rabbitmq-management/pull/201
