### ISSUE TITLE
API endpoint to login via HTTP API or authProxy settings

### ISSUE THREAD

**Issue by sagarmah** [rabbitmq/rabbitmq-management#272]
I have a nodejs application where I authenticate users against LDAP and they get access to several applications one of them being RabbitMQ management GUI hosted on another server. I need some way to log in the user directly to his dashboard bypassing the login page. Is there an endpoint where I can pass his credentials or is there a way to use them in querystring?
Thanks

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
You have two options:

 * Use RabbitMQ LDAP plugin so that RabbitMQ itself authenticates against LDAP
 * Pass credentials in URI hash — we DO NOT recommend or advertise or document this for obvious reasons but there is no way around it sometimes — like so: `https://{hostname}:15672/#/login/{username}/{password}`. Only use this with HTTPS and on internal networks.

**Comment by sagarmah** [comment]
Thank you, I am using https and everything is on internal networks, so the second option will be fine. Will post questions in other communities next time onwards. Thanks.
