### ISSUE TITLE
management plugin displays wrong connection

### ISSUE THREAD

**Issue by hoalequang** [rabbitmq/rabbitmq-management#276]
Hi team,
I'm using management plugin (RabbitMQ 3.6.2) to monitoring my rabbitmq cluster. But I recognize that there are some ghost connections in GUI management. I checked those connections (by netstat -pantl | grep <IP>) but they do not exists. I also checked the log files but there no log info about those connections.
Could you please help me resolve or tracking my issues? 
Many thank!

![image](https://cloud.githubusercontent.com/assets/20273769/17730846/e4a390a6-6494-11e6-82d8-34c7db6a4884.png)

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
Management plugin's stats DB is event-driven. If a connection dies without a chance to emit a closure event, it will be [cleaned up eventually](https://github.com/rabbitmq/rabbitmq-management/issues/198). If the stats database cannot keep up it will intentionally drop some events. Both of those occurrences are rare.

On a related note, you probably want to upgrade form 3.6.2 because that version has known management plugin bugs, including a couple of memory leaks.
