### ISSUE TITLE
Implement a rest_terminate/2 callback function on all HTTP API handlers

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-management#281]
Cowboy offers us the option to carry out some termination procedures on completion, or failure, of RESTful HTTP requests, through the `rest_terminate/2` callback. We currently aren't implementing this function on all management API handlers. We can start off by having these do nothing but return `ok` (unless otherwise, for obvious cases), then going forward, consider a couple of resources to free up/terminate, if any, on a per call basis.

**Comment by essen** [comment]
I do not recommend this. Freeing resources should be done from a separate process with the use of monitors, automatically (just like what happens when you open a file). Like all terminate functions in Erlang, rest_terminate/2 is not fool-proof, and is there only for very specific use cases where monitors wouldn't work (in a perfect world this should never happen, but sometimes you have to deal with badly written software).
