### ISSUE TITLE
Deleting a binding with `rabbitmqadmin` with empty properties key should be clearer or documented

### ISSUE THREAD

**Issue by s0rc3r3r01** [rabbitmq/rabbitmq-management#304]
Deleting a binding with an empty properties_key should be correctly documented or described.

The behaviour seems no to be described anywhere, the way I managed to do it, is by usign _"~"_  as properties_key

`rabbitmqadmin delete binding source=XX destination=YY destination_type=queue properties_key="~" --username=YY --password=XX`

**Comment by michaelklishin** [comment]
Are you sure that the tilde wasn't expanded to `$HOME` in the above example (that is, the key is that the value wasn't actually empty)?

**Comment by s0rc3r3r01** [comment]
hi Micheal, yes sure, it looks pretty unlogical to have my home folder as properties_key...

**Comment by michaelklishin** [comment]
OK, I'll assume this was a shell expansion artifact then.

**Comment by fozboz** [comment]
It isn't.
```
$ rabbitmqadmin declare binding source=anexchange destination=aqueue destination_type=queue
binding declared
$ rabbitmqadmin list bindings source destination routing_key properties_key | grep anexchange
| anexchange | aqueue    |             | ~              |
```
Same happens when creating a binding with the Web UI. When a routing key is specified, the properties key gets set to the same value.
What is the properties key for and why is it needed to delete a binding?

**Comment by michaelklishin** [comment]
It is needed because it's a field on both `{queue,exchange}.bind` and `{queue,exchange}.unbind` protocol methods. You can set it to an empty string. I agree that it should be the default but when it comes to the HTTP API and `rabbitmqadmin`, it's complicated because it's an arbitrary map of keys and values that has to be an endpoint path segment, so it has to be/will be encoded.

`rabbitmqadmin` is a zero dependency Python script. Feel free to take a look and suggest changes via pull requests. They will be considered.

**Comment by IvanKaloyanov** [comment]
Hi, [this](https://github.com/rabbitmq/rabbitmq-management/pull/779) is now merged so as it is for the create binding, now you don't have to explicitly set value for `properties_key` when you want to delete a binding with empty `properties_key`

**Comment by michaelklishin** [comment]
And #779 will ship in `3.8.3`.
