### ISSUE TITLE
statistics_db_node inaccurate after failing to cluster

### ISSUE THREAD

**Issue by jmwilkinson** [rabbitmq/rabbitmq-management#359]
After attempting to cluster node02 with node01, the value for "statistics_db_node" will be node01. This is despite the failure to cluster (due to different rabbitmq versions).

This value will persist even past a rabbitmq restart AND a rabbitmq reset.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Sorry but as of #236 we are no longer looking into issues with the previous architectuer.

**Comment by michaelklishin** [comment]
Statistics node resides on a single node in releases up to 3.6.7 (currently at RC3). I'm not sure why it should move in either successful or unsuccessful cluster expansion case. Anyhow, as of #236 this is irrelevant since there is no dedicated stats DB node anyway: all nodes store their own stats and aggregate when handling HTTP API requests.
