### ISSUE TITLE
unable to connect Rabbit MQ from local machine through php

### ISSUE THREAD

**Issue by kuldeep1984** [rabbitmq/rabbitmq-management#371]
Hi, I have set up RabbitMQ free plan lemur. and try to connect it through php with php-amqplib  module.
But unable to connect it. it responds me with this - 
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /var/www/html/rabbit-mq/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:207

`The PHP Code -
 require_once(DIR . '/vendor/autoload.php');

define("RABBITMQ_HOST", "clam.rmq.cloudamqp.com");
define("RABBITMQ_PORT", 5672);
define("RABBITMQ_USERNAME", "XXXXXXXXX");
define("RABBITMQ_PASSWORD", "XXXXXXXXXXXXXXXXXXXXXXXX");
define("RABBITMQ_QUEUE_NAME", "XXXXXXX");
$connection = new \PhpAmqpLib\Connection\AMQPStreamConnection(
    RABBITMQ_HOST,
    RABBITMQ_PORT,
    RABBITMQ_USERNAME,
    RABBITMQ_PASSWORD
);
`

But I am successfully connect my localserver setup. Please help

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Unfortunately Google Groups decided to mark rabbitmq-users as "malicious content" yesterday without providing a reason. We are looking into possible solutions but using GitHub issues for questions is not one of them. Please post your question to Stack Overflow in the meantime.
