### ISSUE TITLE
Combine vhost limits with vhost management

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-management#388]
Management UI and API have separate pages/commands in 3.7.500.14 for creating vhosts and setting max queues/connections limits. It would be more intuitive if we could supply limits at the time we create the vhost (rather than after the fact go to another page or call different API), and if we could update limits on the vhost details page (where we set user permissions).

**Comment by michaelklishin** [comment]
Sorry but I don't think we should be combining two separate pages or API endpoints that do separate things. Many users will continue creating vhosts without any limits.

In the HTTP API case it would save a line or two of code. I don't think we are willing to sign up for more complexity, validations and tests for that.

**Comment by uvzubovs** [comment]
Many users create queues without attributes, yet specifying and displaying queue attributes is integrated into the queue details page.

**Comment by michaelklishin** [comment]
I'm not sure what you mean by "attributes" but a queue cannot exist without properties such as durable, exclusive, auto-delete. The UI simply provides reasonable defaults. A vhost without limits is perfectly fine and the only reasonable default I can think of is "no limits" because that's who it's been for a decade.

**Comment by uvzubovs** [comment]
Attributes like x-queue-mode, x-max-length, x-message-ttl, etc.
