### ISSUE TITLE
Regular expression filter values need %-encoding

### ISSUE THREAD

**Issue by sapostolou** [rabbitmq/rabbitmq-management#419]
There seems to be an issue with the plus operator in the regexp for filtering queues.

I'm trying to filter queues whose name is of type:
`q-<any string>-<a specified integer>`

The regex I'm using is q-[^-]+-(1|2)\b for filtering queues ending in 1 or 2. This doesn't seem to work. It works though if I replace + with *, but I need to make sure that no queue matched has no string between the two -.

Some examples:
```
q-string1-1 // Expect match
q-string2-2 // Expect match
q-string3-3 // Expect no match
q--3 // Expect no match
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by lukebakken** [comment]
As @michaelklishin pointed out, this question belongs on [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users)

Having said that, @sapostolou you are not using the correct regex. You should be using `q-[^-]+-[12]$`:

```
5> S0 = "q-frazzle-0".
"q-frazzle-0"
6> S1 = "q-frazzle-1".
"q-frazzle-1"
7> S2 = "q-frazzle-2".
"q-frazzle-2"
8> S3 = "q-frazzle-3".
"q-frazzle-3"
9> [ re:run(S , "q-[^-]+-[12]$") || S <- [S0, S1, S2, S3] ].
[nomatch,{match,[{0,11}]},{match,[{0,11}]},nomatch]
```

**Comment by sapostolou** [comment]
@lukebakken I created 4 queues like the ones you used and neither of them matched with this regex. I'm trying to match them via the management UI of RabbitMQ version 3.6.10.

Also, I used the parenthesis instead of the brackets because the numbers after the second dash aren't necessarily single digits

**Comment by lukebakken** [comment]
@sapostolou - I have a couple things to report

> I used the parenthesis instead of the brackets because the numbers after the second dash aren't necessarily single digits

Parens won't help you here. If you want to match queues ending with something like `-N2` or `-N1`, where `N` can be any number of digits, you would use this regex: `q-[^-]+-[0-9]*[12]$`

I used the chrome dev tools to see what request is sent when you filter queues:

```
http://localhost:15672/api/queues?page=1&page_size=100&name=q-[^-]+-[12]$&use_regex=true&pagination=true
```

Notice that neither the `+` sign nor any part of the regex is url-encoded. If I use `curl` on the command line to execute that query but also have it do url-encoding, notice that the regex is encoded (response is truncated):

```
$ curl -4vvv -G 'http://localhost:15672/api/queues' --data-urlencode 'name=q-[^-]+-[12]$' --data-urlencode 'use_regex=true' --data-urlencode 'pagination=true' -H 'authorization: Basic Z3Vlc3Q6Z3Vlc3Q='
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15672 (#0)
> GET /api/queues?name=q-%5B%5E-%5D%2B-%5B12%5D%24&use_regex=true&pagination=true HTTP/1.1
> Host: localhost:15672
> User-Agent: curl/7.54.1
> Accept: */*
> authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
> 
< HTTP/1.1 200 OK
< server: Cowboy
< date: Tue, 20 Jun 2017 17:42:43 GMT
< content-length: 4941
< content-type: application/json
< vary: accept, accept-encoding, origin
< Cache-Control: no-cache
< 
[{"messages_details":{"rate":0.0},"messages":0,"messages_unacknowledged_details":{"rate":0.0},"messages_unacknowledged":0,"messages_ready_details":
...
```

Thanks for reporting this bug and keep an eye here for when a fix is shipped.
