### ISSUE TITLE
rabbitmqadmin command not found

### ISSUE THREAD

**Issue by yogeshVU** [rabbitmq/rabbitmq-management#431]
I have installed the rabbitmq and enabled the rabbitmq-management plugin. But when tried to invoke the rabbitmqadmin command it says command not found.

```
root@98d6c6a24fef:/usr/local/bin# rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   * = running on rabbit@98d6c6a24fef
 |/
[e*] amqp_client                       3.6.10
[e*] cowboy                            1.0.4
[e*] cowlib                            1.0.2
[  ] rabbitmq_amqp1_0                  3.6.10
[  ] rabbitmq_auth_backend_ldap        3.6.10
[  ] rabbitmq_auth_mechanism_ssl       3.6.10
[  ] rabbitmq_consistent_hash_exchange 3.6.10
[  ] rabbitmq_event_exchange           3.6.10
[  ] rabbitmq_federation               3.6.10
[  ] rabbitmq_federation_management    3.6.10
[  ] rabbitmq_jms_topic_exchange       3.6.10
[E*] rabbitmq_management               3.6.10
[e*] rabbitmq_management_agent         3.6.10
[  ] rabbitmq_management_visualiser    3.6.10
[  ] rabbitmq_mqtt                     3.6.10
[  ] rabbitmq_recent_history_exchange  3.6.10
[  ] rabbitmq_sharding                 3.6.10
[  ] rabbitmq_shovel                   3.6.10
[  ] rabbitmq_shovel_management        3.6.10
[  ] rabbitmq_stomp                    3.6.10
[  ] rabbitmq_top                      3.6.10
[  ] rabbitmq_tracing                  3.6.10
[  ] rabbitmq_trust_store              3.6.10
[e*] rabbitmq_web_dispatch             3.6.10
[  ] rabbitmq_web_mqtt                 3.6.10
[  ] rabbitmq_web_mqtt_examples        3.6.10
[  ] rabbitmq_web_stomp                3.6.10
[  ] rabbitmq_web_stomp_examples       3.6.10
[  ] sockjs                            0.3.4
root@98d6c6a24fef:/usr/local/bin# rabbitmqadmin
bash: rabbitmqadmin: command not found

```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ plugins do not modify `PATH`.  `rabbitmqadmin` is a zero dependency Python tool that can be [obtained from a running node with management plugin enabled](http://www.rabbitmq.com/management-cli.html) or [downloaded from GitHub](https://github.com/rabbitmq/rabbitmq-management/blob/stable/bin/rabbitmqadmin).

**Comment by yogeshVU** [comment]
What do you mean "rabbitmqadmin is a zero dependency Python tool that can be obtained from a running node with management plugin enabled " ?
As can be seen I have already enabled it. How can I set rabbitmqadmin to the PATH? Where is the rabbitmqadmin python tool located on unix?

**Comment by michaelklishin** [comment]
@yogeshVU "zero dependency" means that it only needs a supported Python version to run, no 3rd party libraries or tools.

Since it's a zero-dependency script it can be placed into any directory on your `PATH`. There is no shortage of information on the Web about how to do that, `rabbitmqadmin` is not special.

**Comment by yogeshVU** [comment]
Thanks for the info. I downloaded the script and able to use it in command line mode !

**Comment by spinningcat** [comment]
i am in windows 10 there is no rabbitmqadmin here. Is there away to clean content of rabbitmq programatically. I am using c#.

**Comment by michaelklishin** [comment]
This is not a support forum.

`rabbitmqadmin` can be downloaded from a running node or GitHub, as mentioned above. Both AMAP 0-9-1 and HTTP API support queue purging (or deletion).
