### ISSUE TITLE
Queued messages chart incorrect for last 8 hours time period

### ISSUE THREAD

**Issue by tomjonandy** [rabbitmq/rabbitmq-management#475]
![screen shot 2017-09-11 at 11 32 21](https://user-images.githubusercontent.com/18629789/30270810-e832b43e-96e5-11e7-91fe-2a73970a1711.png)
As can be seen from the screenshot, the x-axis only covers the last hour. I am unsure as to whether the actual data in the graph is for the 8 hour period or not.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
We can't be sure either: we have no version information or a way to reproduce. Was the node actually running for at least 8 hours? We don't know that either. Please start a mailing list thread.

**Comment by lukebakken** [comment]
@tomjonandy - I just double-checked using `rabbitmq_v3_6_12_rc3` and the UI updates as expected when a different time period is chosen. I'm using Chrome 60 on OS X.

**Comment by tomjonandy** [comment]
Maybe put that massive block of advice in CONTRIBUTING.md to avoid issues being created in the future when they are just going to be closed?

**Comment by lukebakken** [comment]
@tomjonandy - we can continue investigation if we have information with which to work. We aren't dismissing your report but can't do anything with it without more details. Please feel free to provide them and re-open this issue (and include browser version and operating system version running the browser). Thanks!

**Comment by tomjonandy** [comment]
@lukebakken (Sorry, I sent that comment before your first came through...) I am running rabbitmq 3.9.11, firefox 52.2.1 OS X. It is only the 8 hours time frame which doesn't work, and only that specific graph (the queued messages one). The node has definitely been running for significantly longer than 8 hours.

**Comment by lukebakken** [comment]
Thanks @tomjonandy I will check that out. I have a couple more questions -

* Is this a development workstation?
* If so, has it been put into sleep or hibernation at any point during which RabbitMQ was running?

**Comment by tomjonandy** [comment]
Sorry, i should have been clearer, rabbitmq is running on a cluster of 3 nodes, all running Ubuntu 16.04.3 LTS. The workstation running firefox will have been put to sleep, although I am unsure whether that is relevant.

**Comment by tomjonandy** [comment]
I have just noticed that the "Last day" time period also seems to display similarly incorrect behaviour (again, only for that specific graph as far as I can tell)

**Comment by lukebakken** [comment]
@tomjonandy thanks for that detail. So this is limited to just "Queued messages" on the "Overview" page and no other graph? Does force-reloading the page or restarting the browser resolve the issue?

**Comment by tomjonandy** [comment]
@lukebakken actually this is the graph when you look a specific queue on the queues page, sorry for the confusion.

**Comment by michaelklishin** [comment]
@lukebakken did you get any further with this? do we have a summary of the findings so far?

**Comment by lukebakken** [comment]
I'm going to look at it today.

**Comment by lukebakken** [comment]
I can't reproduce this using FF `52.0.1` on Arch Linux.

**Comment by chriskallen** [comment]
We have been seeing this exact same behavior with our production rabbit cluster also.

We cannot see the queue specific metrics for last 8 hours (shows only last 50 mins) or last day (shows only 30 mins) 

The graph appears to show the data at the granularity of the requested timespan but only for the limited period i.e there are very few points on the graph.

I have opened brand new browsers (no cookies) and can replicate in both Chrome and Edge.

**Comment by chriskallen** [comment]
Looking at the Json returned in the call there are only a few Samples returned.  Here is the Url that is being called to gather the data:

http://xxxx:15672/api/queues/xxxxQueueNamexxxx?lengths_age=28800&lengths_incr=600&msg_rates_age=28800&msg_rates_incr=600&data_rates_age=28800&data_rates_incr=600

**Comment by lukebakken** [comment]
@chriskallen - thanks for the report. We haven't seen this behavior in any of our long-running test environments. Could you provide more details about your environment, such as RabbitMQ version, operating system distro and version? Or, you can run [this script](https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env) and securely provide the generated archives for me to investigate. Note that the script does *not* scrub or protect any data that may be in log files. Thanks.

**Comment by chriskallen** [comment]
Watching it now - it appears to be to do with the time of when the requests are made.  

For a few minutes (can't be specific) it was return 1hr 50 mins of data.  Then when the next 10 mins on the clock ticked over it went back to 50 mins.

Currently running: RabbitMQ 3.6.10, Erlang 19.3 on Windows 2012 r2

As we are running on windows can't run your script, sorry.

**Comment by lukebakken** [comment]
Based on the URL you posted, it looks like you're running the browser on another machine. It *shouldn't* matter, but is the other machine in the same time zone as the RabbitMQ node it's connecting to? Are the clocks in sync?

**Comment by chriskallen** [comment]
We set our servers to UTC, opening the browser (don't tell my security team) on the server and we have the same problem.

**Comment by lukebakken** [comment]
OK, thanks for continuing the discussion. Without a reliable reproducing scenario, it doesn't make sense for me to continue guessing what could be wrong 😄 

There are ways to [reset the statistics database](https://www.rabbitmq.com/management.html#stats-db). If you'd like to give it a try, you could run this command on one node which will reset the stats on all nodes:

```
rabbitmqctl eval "rabbit_mgmt_storage:reset_all()."
```

I would be interested to know if this resolves your issue. If the above command produces any unexpected or interesting output, please post it here.

**Comment by chriskallen** [comment]
It is now drawing the graph for the last 8 hours (obviously it is empty).

I have the data from the bad requests, will dig into the data and the source and see if I can see any reason.

**Comment by lukebakken** [comment]
Thank you for the continued reports.

**Comment by chriskallen** [comment]
Coming back to it this morning it is broken again:
![image](https://user-images.githubusercontent.com/588608/31006021-03dec23e-a4f3-11e7-8964-992af09aeb4b.png)

**Comment by chriskallen** [comment]
More than happy to run any commands on the server to try and diagnose

**Comment by michaelklishin** [comment]
@chriskallen please upgrade to 3.6.12 before you spend any more time investigating. Since you run on Windows, [keep this issue in mind](https://github.com/rabbitmq/rabbitmq-server/issues/1343). We do not use GitHub issues for investigations, RCA and so on, so let's move this to rabbitmq-users.

**Comment by michaelklishin** [comment]
A couple of issues can seem relevant here and were addressed since 3.6.10:

 * https://github.com/rabbitmq/rabbitmq-management/issues/404
 * https://github.com/rabbitmq/rabbitmq-server/issues/1340

So let's continue on the mailing list and against 3.6.12 (or 3.6.13, when it comes out in a week or two).

**Comment by caliloo** [comment]
Hi,

 I'm having this issue too  on 2 servers I've just installed a couple of days ago.

I'm running rabbitmq-server.noarch     3.7.2-1.el7 on centos 7.4
and I'm browsing the stats using the latest firefox (52.5.1) on a cetos7.4 client (up to date).

quick html debugging shows that the page/frame (I'm not that great at html things) to choose the actual values (such as 3600|60, or 28800|600) for the span and resolution of the graph are ok.

It just seems that the image that is loaded for the graph then choosing the 8hrs (or 24hrs) radio element is not correct (the image always shows around 1hr worth of data, but at something that looks like the right sampling for the period chosen). It seems it is merely a boundaries problem on the graph generated. I'm at a loss to explain why it happens.

I've only tested permanent queue. I'm can only say it happen when looking at messages stats on a permanent queue. (on 2 different servers, same browser -but individual tests-). the servers have been running for more than 8 hours.

Happy to check anything someone might is worthy to try.

Cheers,
Charles.

**Comment by ric2b** [comment]
I was seeing the same issue on 3.6.10. Updated to 3.6.15, no improvement.
The issue happens both on Chrome and Firefox, on Ubuntu 16.04.
The issue happens both on the docker container on my machine and the rabbitmq instance running on a RHEL system.

Also using permanent queues,
Can also confirm that the request parameters are ok but the response only returns a few samples from the last hour or two.
This only happens when seeing the graph for a specific queue, it works fine on the overview page.

**Comment by phaddius** [comment]
This is also happening for me. Last Eight Hours and Last Day are not showing the proper time frame. It DOES work properly on Mac Safari though.

**Comment by linjunzhu** [comment]
I got a same problem.

Last Eight Hours and Last Day is show incorrect. It always show one hours data.

**Comment by marek-obuchowicz** [comment]
👍 same issue on v3.6.15 with erlang 19.2.1

**Comment by ketanbhatt** [comment]
Same issue on v3.6.14 with Erlang 20.1. Tested on Safari too (as reported by someone earlier that it was working on that), and the same issue exists.

**Comment by lukebakken** [comment]
While we appreciate the reports of this issue on various `3.6.x` versions, please note that the latest `v3.6.x` version is `3.6.16` at the moment. In addition, support for the `3.6.x` series will end at some point.

As far as I know, this issue has not been reported for any `v3.7.x` version.

Finally, without a reliable (or semi-reliable) means to reproduce this the team can't do much about this issue and must prioritize other work.

**Comment by caliloo** [comment]
I have reported this issue on 3.7 further up the thread. I have also provided you with an exact centos 7 version for web client and rabbitmq server at the time. So you sure dont look like you have much motivation solving this (can't you just spin up 2 VM and create a load that has a peak in it so you see if your graph is reporting the right thing ?). You could at least give us a hint as to where the code for this graph's generation lies on the client side of the visualisation, since it looks radio button related.  If you are not bothered looking into it, Fair enough, but pushing this back on the different people as "you can't give me the right info" is a bit cheap I find. Without explaining a bit more how this thing works behind the scene to make this graph, it is difficult for external people to find other degrees of freedom along which to test to find a reproducible setup.

If you believe that it's a heisenbug (which is entirely possible) I'm happy to look into this if I try rabbitmq again later on, but I'm not going to wade thru the entire code base on my own... json or html just isnt my kind of fun right now. So up to you now :)

**Comment by marek-obuchowicz** [comment]
Hello @lukebakken,
I have a few clusters on which this issue appears regularly. Not sure if this is related, but I'm connecting to RMQ GUI via AWS ELB and SSH tunnel.

I'll be happy to provide you a dump of the environment. I see however one single problem. All our clusters run on AWS Autoscaling groups. If i shut down RMQ, loadbalancers will quickly recognize it and kill instances / create a new ones.
Is there any other way than stopping the nodes to provide you a working environment dump? I can choose one of staging clusters and completely stop any traffic - disconnect all consumers and producers, execute any action like flush to disk (if sth. like that exists?) and provide a copy of configuration / data directories. But if possible, i don't want to stop the nodes for reason given above. Would it be any kind of helpful for you?

I'm using RMQ 3.6.15 on Erlang 19.2.1

**Comment by lukebakken** [comment]
@marek-obuchowicz I'll see if there is a less drastic way to get information from one of your environments that exhibit this issue.

**Comment by caliloo** [comment]
@lukebakken thanks for coming back to us with a bit more to chew on.

I can't go look into this right now, because the project using rabbitmq is on hold for another 3-4 weeks, but I can contrast some things compared to your test setup.
All my servers were latest vanilla centos long-running rented servers (different continents, different host providers) single node rabbitmq. The (vanilla centos) webclient was connecting via ssh tunneling to the servers (more than one at a time, using a different port client side for tunneling). The problem with the graph was systematic then, no matter which server I was trying. So clearly there is a detail in that setup that makes this more systematic than in your setup. 
Any chance that you can try this in a single node vm rather than in your redundant nodes test env ? clicking thru centos install and following the rabbitmq (https://www.rabbitmq.com/install-rpm.html bintray) page is pretty much what I did.

Can you also drop us a couple of lines on how to pull data out of the stats db directly, that is a check I can do next time I hit this issue, to determine if the webcode or the backend is responsible...(I don't know if the image is made client side or server side ...).

**Comment by lukebakken** [comment]
There is a very specific piece of information that is _easy to overlook_ because it is only mentioned in [this comment](https://github.com/rabbitmq/rabbitmq-management/issues/475#issuecomment-328577404):

> actually this is the graph when you look a specific queue on the queues page, sorry for the confusion.

This is *not* the "Overview" page, but the page that is shown when a single queue is clicked. Good news for everyone - I do see this issue in our long-running environment when I view a single queue.

**Comment by caliloo** [comment]
haha, great news !

**Comment by dcorbacho** [comment]
The behaviour seems to be related to the retention policies, as the queue stats use the `basic` policy while the vhost stats used in the overview page use the `global` policy. That is, we do not have such detailed data for the queues. It is possible to configure RabbitMQ to store more detailed stats, but that will also increase the memory consumption of the management plugin. The configuration of the management agent can be changed so that the retention policy for `basic` mimics that for `global`.

@lukebakken will verify this and provide a final update.

**Comment by lukebakken** [comment]
Based on the [source code](https://github.com/rabbitmq/rabbitmq-management-agent/blame/master/src/rabbit_mgmt_data.erl#L506), this has been the default behavior for at least 2 years, probably more.

I'm verifying this behavior now, but it will take at least 8 hours. If someone here would like to test this out, you can use the following `rabbitmq.conf` configuration:

```
management.sample_retention_policies.global.minute  = 5
management.sample_retention_policies.global.hour    = 60
management.sample_retention_policies.global.day     = 1200

management.sample_retention_policies.basic.minute = 5
management.sample_retention_policies.basic.hour   = 60
management.sample_retention_policies.basic.day    = 1200

management.sample_retention_policies.detailed.10 = 5
```

If you're using the old school Erlang term configuration in `rabbitmq.config` or `advanced.config`, this is what it looks like:

```
[
    {rabbitmq_management, [
        {sample_retention_policies, [
            {global, [{86400,1200},{3600,60},{60,5}]},
            {basic, [{86400,1200},{3600,60},{60,5}]},
            {detailed,[{10,5}]}
        ]}
    ]}
].
```

Docs for these settings can be found [here](https://www.rabbitmq.com/management.html#sample-retention).

**NOTE:** this _will_ increase memory use as more stats are saved.

In the interest of reducing confusion we may remove the "Last 8 hours" and "Last day" radio buttons if the retention policy does not provide that data.

**Comment by lukebakken** [comment]
I have confirmed that the `sample_retention_policies` configuration in [this comment](https://github.com/rabbitmq/rabbitmq-management/issues/475#issuecomment-440768252) will resolve this issue.

Once again, note that storing more data will result in more memory use. If you need historical data for your queues, it is a better option to set up dedicated monitoring: [link](https://www.rabbitmq.com/monitoring.html).

We will consider modifying the UI to reduce confusion around choosing time periods for which no stats exist.
