### ISSUE TITLE
Listing Many Queues is Slow

### ISSUE THREAD

**Issue by bradjorgensen** [rabbitmq/rabbitmq-management#50]
I have a RabbitMQ cluster with about 6000 queues.  When viewing the queues through the management interface, it takes about 8-9 seconds to start sending the response and about 3 seconds to transfer the response.  The transfer time can probably be helped by supporting compression, but other than compression or making the result more concise, the transfer time is not the responsibility of the management plugin.  The time is the same whether I'm explicitly sorting the list or not.  I'm not sure how it's getting the list of queues, but I think it should be much faster.

**Comment by michaelklishin** [comment]
Yes, this is a known issue.

**Comment by rtraschke** [comment]
I've run some profiling on the queue display of the management UI using fprof (module rabbit_mgmt_wm_queues). A first glance points to the formatting being done by the rabbit_mgmt_format module as the main time sink (roughly ¾ of the total time taken).

I'll have a deeper look into this to see if anything reasonably obvious can be done to speed this up.

**Comment by michaelklishin** [comment]
@rtraschke are you sure it's not because we load and render way more than a single page of results?

**Comment by rtraschke** [comment]
@michaelklishin I noticed that all queues get transmitted back to the browser, but only a subset are rendered, there's already paging in place in the UI. But as far as I can see, the time to ship the data is dwarfed by the time to format it server side. I'll try and collate the numbers and post them later.

**Comment by rtraschke** [comment]
See the Chrome timings for opening the queues pane in the presence of 12000 queues. All of the time is spent between the request getting sent and the first byte getting delivered back to the browser. That is, the time is spent mostly server side.
<img width="1222" alt="screen shot 2015-08-27 at 10 33 13" src="https://cloud.githubusercontent.com/assets/758769/9516184/4938e9aa-4ca7-11e5-8958-56a5a28f6dd8.png">

And my profiling of the server code in rabbit_mgmt_wm_queues indicates this (this was with 6000 queues, also best look at times as relative, not absolute, due to profiling overhead):
```
%                                               CNT       ACC       OWN        
[{ totals,                                     2154433,17712.489,17131.496}].  %%%

%                                               CNT       ACC       OWN        
[{ "<7278.7533.3>",                            2154433,undefined,17131.496}].   %%

% SNIP ....

{[{{rabbit_mgmt_format,strip_pids,1},          2432, 9998.131,   21.553},      
  {{rabbit_mgmt_format,queue,1},               6000, 3919.756,   51.035}],     
 { {rabbit_mgmt_format,format,2},              8432,13917.887,   72.588},     %
 [{{rabbit_mgmt_format,'-format/2-lc$^0/1-0-',2},8432, 9313.427,  978.853},      
  {{lists,concat,1},                           8432, 4531.872,   37.285}]}.    

% SNIP ...
```
The combined format invocations (13917.887) make up ~75% of the time taken to produce the result sent back to the browser (17712.489).

**Comment by rtraschke** [comment]
And fair enough, on a slow connection, shipping the all the data will also take longer. The lower the bandwidth, the longer the final "Content Download" will take. We can look at compression for this perhaps. But it's the server side packaging of the data that appears to be the initial culprit. So, I'd like to concentrate on that first.

**Comment by michaelklishin** [comment]
@rtraschke so if we have 1M queues and need to render 100, we'd load, render and return 1M. I think there's a bigger fish to catch than enabling compression.

**Comment by videlalvaro** [comment]
Isn't the problem here that listing queues doesn't do any server side paging at all? I'd assume formatting 1M items would always take long

**Comment by carlhoerberg** [comment]
If you're logged in with a user that only got access to a vhost with few
queues, it still takes as long time for them to list their queues as for
someone with access to all (possible thousands of queues) to list the
queue page.

**Comment by michaelklishin** [comment]
I confirm discovering the same thing as @carlhoerberg: we don't even take the vhost filter into account. Related: https://github.com/rabbitmq/rabbitmq-management/issues/34.

**Comment by videlalvaro** [comment]
So then we have two things to do:

a) Improve performance for the single queues case.
b) Improve performance for the many queues case as the issue suggests.

**Comment by michaelklishin** [comment]
@videlalvaro sorry, do you mean "for a single vhost" and "multiple vhosts"?

**Comment by rtraschke** [comment]
OK, we now have two separate problems:

First, server side packaging of lots of queues is slow. And the profiling tells me that it is the invocations of `rabbit_mgmt_format:format/2` that are taking the time.

Second, if a user is logged in and can only see some vhosts, the management UI still fetches all queues and filters on vhost afterwards. (_Note_, this is different from using the REST api `/queues/:vhost` or the `rabbitmqadmin.py -V vhost list queues`! These two only fetch queues from the designated vhost.)

**Comment by rtraschke** [comment]
As a follow on, but a much bigger job, you could have real paging on the UI side and support that with server side paging.

At the moment you seem to only get the option to show the first N (0 - all) results, whatever they may be.

**Comment by michaelklishin** [comment]
@rtraschke pagination sounds like a pretty essential thing here. If that's what we need to make the UI more efficient regardless of how many queues there are, lets add it to the scope. Currently folks who run or use shared clusters (e.g. Carl) eventually find management UI unusable.

**Comment by rtraschke** [comment]
Finally, the reason why server side packaging is so costly, becomes evident whan you look at the output of /api/queues. The JSON constructed on the server contains all you ever wanted to know about your queues! So, a really easy way to speed things up is to decide what actually needs to be transported back from the server.

For example (from my second vhost, /api/queues/second):
```JSON
[
 {
  "memory":21920,
  "messages":0,
  "messages_details":{"rate":0.0},
  "messages_ready":0,
  "messages_ready_details":{"rate":0.0},
  "messages_unacknowledged":0,
  "messages_unacknowledged_details":{"rate":0.0},
  "idle_since":"2015-08-27 11:41:06",
  "consumer_utilisation":"",
  "policy":"",
  "exclusive_consumer_tag":"",
  "consumers":0,
  "recoverable_slaves":"",
  "state":"running",
  "messages_ram":0,
  "messages_ready_ram":0,
  "messages_unacknowledged_ram":0,
  "messages_persistent":0,
  "message_bytes":0,
  "message_bytes_ready":0,
  "message_bytes_unacknowledged":0,
  "message_bytes_ram":0,
  "message_bytes_persistent":0,
  "head_message_timestamp":"",
  "disk_reads":0,
  "disk_writes":0,
  "backing_queue_status":{"q1":0,"q2":0,"delta":["delta","undefined",0,"undefined"],"q3":0,"q4":0,"len":0,"target_ram_count":"infinity","next_seq_id":0,"avg_ingress_rate":0.0,"avg_egress_rate":0.0,"avg_ack_ingress_rate":0.0,"avg_ack_egress_rate":0.0},
  "name":"foo0000",
  "vhost":"second",
  "durable":true,
  "auto_delete":false,
  "arguments":{},
  "node":"rabbit1@Robbys-MacBook-Pro-2"},
"..."
]
```

**Comment by rtraschke** [comment]
@michaelklishin OK, then I'll need a decision. Which of these two should we do first to address the issue:

1. Implement pagination.
2. Improve client - server interaction to reduce server side effort required to produce results.

For 2., in more words: Have the UI tell the server which fields it needs for queues, and potentially which vhost(s) to retrieve from, and have the server only package what was requested.

**Comment by michaelklishin** [comment]
@rtraschke we should exclude `backing_queue_status`, it is an implementation detail that spilled over.

**Comment by michaelklishin** [comment]
@rtraschke pagination sounds more important to me.

**Comment by michaelklishin** [comment]
Ugh, now I realise we have `head_message_timestamp` in the backing queue status. That's a useful thing to have (and a recent contribution), we may consider moving it out of `backing_queue_status` first.

@alexethomas WDYT?

**Comment by alexethomas** [comment]
@michaelklishin it's not in backing_queue_status any more - it was at one stage though.

**Comment by carlhoerberg** [comment]
@rtraschke no, limiting the columns, with ?columns=name, does not speed things up. I assume that everything is calculated, then, at a later stage, vhost filtering, columns filtering etc. is applied. Pagination won't help either if it's done as a later step. Hopefully all filtering/pagination could be done before producing the output.

**Comment by rtraschke** [comment]
@carlhoerberg Yeah, I meant adding that into the mix, changing the server to only collate the fields and queues you want. But proper pagination (not just fancy table work in UI, but server side pages) appears more urgent, so that'll happen first. If it's possible to combine the two changes, then that might happen, but I don't know that yet.

**Comment by michaelklishin** [comment]
I think early filtering by vhost is also fairly essential and combined with (server-side) pagination should speed things up considerably for scenarios with many queues (which is exactly where what we have is a pain point in the first place).

**Comment by rtraschke** [comment]
I've been trying to get my head around how paginating the queues list would work. There are two main ways of doing pagination: _infinite scrolling_ and _paging links_. We shall discount infinite scrolling, since that would only delay the latency we are seeing when fetching the queue list to a later point.

For paging links, two main approaches exist: _count & offset_ based or _cursor_ based. The count & offset based approach is good for static data, but becomes problematic when dealing with changing underlying data.

This essentially leaves cursor based pagination for the queue listing. Using a cursor for pagination, necessitates a sorted set of unique IDs for each queue that gets listed. We can use the `amqqueue.name` field for this (a `#resource{}` record), and ensure that results are sorted server side, rather than the current client side sorting. That means sorting first by _vhost_ then by _queue name_. I would suggest that the _down_ queues currently displayed at the end either get sorted inline or to the front.

Implementation wise, this means that the `/api/queues` request needs to receive the cursor position and desired page size, and return cursor positions used for _first_, _previous_, _current_, _next_, and _last_ pages. (First and last page cursors are not strictly necessary, but might be useful for providing quick links.)

The auto-update functionality would then reload the queue list based on the current cursor. This would mean that the queue shown at the top of the list of current results would remain at the top, any changes prior would change the previous (and potentially first) cursor values, and any changes in the current view or later would change the next and last cursors. If the queue at the current top of the list is removed, then the code would need to choose the following queue as the current cursor.

Unless anyone has any big concerns about this, I shall try and figure out how we can make these changes.

**Comment by michaelklishin** [comment]
@rtraschke your analysis seems good. I think that the cursor approach still has cases where it may produce unexpected results if the underlying dataset changes. That's true for most data stores and table-like analytics tools.

You also raise a good point about data set sorting: that's a natural feature to ask for in the future. If you feel sort-by-column is a feature we'd be able to provide with the cursor approach, I have no objections.

**Comment by rtraschke** [comment]
@michaelklishin I'll keep general sorting in mind, but we can add that as a second step, not right from the beginning. We don't have it at the moment.

I just mentioned it, because currently the queues are sorted on the client for display, since the query on the server returns whatever order mnesia gives based on a table type of set. But server side sorted data is a prereq for cursor based pagination.
