### ISSUE TITLE
requeue option removed from rabbitmqadmin 3.7.0

### ISSUE THREAD

**Issue by KonstantinCodes** [rabbitmq/rabbitmq-management#521]
since upgrading to version 3.7.0 of the docker image *rabbitmq:management-alpine*, the cli lost the ability to get messages without requeueing.

this command worked in version "rabbitmqadmin 3.6.12":
`rabbitmqadmin get queue=xyz payload_file=payload.json requeue=false`

in the version 3.7.0, it produces following error:
`ERROR: Argument "requeue" not recognised`

**Comment by Gsantomaggio** [comment]
@KonstantinCodes We changed the `get` API with more options.
See https://github.com/rabbitmq/rabbitmq-management/pull/199 

But we had to break the compatibility with the `3.6.x` `get` HTTP API

**Comment by Gsantomaggio** [comment]
@KonstantinCodes 
Please try with `ackmode=ack_requeue_false` instead of `requeue=false`

**Comment by KonstantinCodes** [comment]
@Gsantomaggio Uh thanks a lot!

**Comment by asfaltboy** [comment]
Should this be updated in the docs? @Gsantomaggio would a pull-request be appreciated here?

**Comment by michaelklishin** [comment]
Pull requests would be considered when they cover something missing or unclear in a currently supported release series.

RabbitMQ 3.6 has been out of support for one year. To our knowledge, all the docs are updated to use the arguments available in 3.7. RabbitMQ 3.7 release notes do mention this change. There are no plans to also document what 3.6 has because, well, it's not a supported release series.

**Comment by asfaltboy** [comment]
Sorry for being vague, the documentation I was reading when I stumbled upon this issue is here:"
https://www.rabbitmq.com/management-cli.html

Under example, it has this code snippet, which seems wrong under 3.7:
> And get it back
> ```bash
> rabbitmqadmin get queue=test requeue=false
> ```

Here's a diff of the correction I had in mind:

https://github.com/rabbitmq/rabbitmq-website/compare/live...asfaltboy:patch-1

**Comment by michaelklishin** [comment]
@asfaltboy we definitely would consider a PR for that. Thank you.
