### ISSUE TITLE
Wrong time axis X

### ISSUE THREAD

**Issue by duccanh0022** [rabbitmq/rabbitmq-management#585]
Hello, I have a problem when use RabbitMQ.

<img width="1261" alt="rabbitmq" src="https://user-images.githubusercontent.com/4942484/41773182-5ff2869a-7645-11e8-9472-e9ad2b0754d7.png">

I deployed RabbitMQ on Docker, System's time always later 1 hour with axis X (in every graph...). How do can I fix it?
Thanks you!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'd start by comparing your machine's time zone and that of all cluster nodes (and whether those are in sync). Please post your questions to the mailing list in the future.
