### ISSUE TITLE
Incorrect Messages count in RabbitMQ UI for the Queues

### ISSUE THREAD

**Issue by pankaj405586** [rabbitmq/rabbitmq-management#587]
Issue: in rabbitmq UI no of message count is 100 but same when i trying to get through curl command it's showing zero.
i also tried to fetch message from rabbitmq gui by get message but it's saying queues is empty.

please help why this is happening ?

RMQ version: 3.6.12
No of message in ready state: 602 (as per UI)
No of messages as per curl: 602

curl -i -u devops:******* -X GET http://******:15672/api/queues/growth/domain_q_prod_TransformerHMSEvent |sed 's/,/\n/g' | grep '"messages"' | sed 's/"messages"://g'

trying to fetch message using curl:

curl -i -u devops:****** -H "content-type:application/json" -X POST http://******:15672/api/queues/growth/domain_q_prod_TransformerHMSEvent/get -d'{"count":100,"requeue":true,"encoding":"auto","truncate":50000}'

response: 
HTTP/1.1 200 OK
server: Cowboy
date: Wed, 04 Jul 2018 04:26:08 GMT
content-length: 2
content-type: application/json
vary: accept, accept-encoding, origin
Cache-Control: no-cache
Content-Type: application/json
[]

![screen shot 2018-07-04 at 09 55 40](https://user-images.githubusercontent.com/30307004/42256773-b27e72b4-7f70-11e8-94d3-edef509b5f58.png)
![screen shot 2018-07-04 at 09 55 54](https://user-images.githubusercontent.com/30307004/42256774-b2a98ddc-7f70-11e8-9369-1e00a8f78452.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Management UI uses the same HTTP API but the page you are looking at and the what `basic.get` returns represent different data. I'm not sure where the idea of using `basic.get` with requeueing as a way to determine how many messages there are in a queue comes from. There are [better ways](http://www.rabbitmq.com/api-guide.html#passive-declaration), including in the HTTP API alone.

**Comment by pankaj405586** [comment]
Thanks Michaelklishin,

so do i need to post same issue in rabbitmq-users group ?

**Comment by michaelklishin** [comment]
Our team does not use GitHub issues for questions, discussions, investigations. You haven't provided much background on what you are trying to do, so feel free to post to the list with more details. As explained above, `basic.get` and consumption over HTTP API are far from optimal when it comes to assessing queue state and management UI uses the same API as you would with `curl` but it uses a different endpoint.
