### ISSUE TITLE
Missing vhost selection box on definitions upload

### ISSUE THREAD

**Issue by Ruairidh** [rabbitmq/rabbitmq-management#592]
Hi,

I'm having an issue with the broker definitions import functionality. Starting from a fresh server, I leave the Virtual Host option set to "/" in the box at the top right of the management page. I now import some definitions from file, everything gets imported under the "/" vhost, regardless of the vhost setting in the uploaded file.

I know that if I already have vhosts defined and I upload (or download) broker definitions, there is an selection box to export (or import) only the definitions for a particular vhost. When no vhosts are defined, these boxes are hidden for me.

RabbitMQ 3.7.3
Erlang 20.2
Chrome 67.0.3396.99 64-bit

Not a huge issue I guess, but it confused me for some time!

Thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid I don't understand what the steps and expectations are. Definitions can be exported or imported for all but just one virtual host. It's a UI option and if you import for just one vhost, all others in the definitions file will be ignored.

Please start a rabbitmq-users thread with a bit more details and perhaps an example file we can try. Thank you!
