### ISSUE TITLE
RabbitMQ Management UI and %2f (encoded slash for default virtual host) in the URL path

### ISSUE THREAD

**Issue by sn0wcat** [rabbitmq/rabbitmq-management#602]
There are a lot of pages which use the encoded default virtual host in the path of the url (%2f) . This is not a problem when running the application standalone, but due to a recent update to spring security's
StrictHttpFirewall  the deployments of the management ui on e.g. cloud foundry are not working anymore.

The problem is that %2f is recognized as one of the possibly malicious characters and the infrastructure firewalls are blocking such urls: this makes it impossible to run the management ui on such infrastructure.

Can the  %2f in the url  be encoded differently (e.g. base64) in order to circumvent this problem?

  
* RabbitMQ version
3.6.15 

* Erlang version
Erlang 20.1

* Browser and its version
Chrome 

 * What management UI page was used (if applicable)

multiple pages which use default virtual host name (%2f) in the path of the url.

 * How the HTTP API requests performed can be reproduced with `curl`
Here is one example
https://somecloudfoundry.instance/api/exchanges/%2F?page=1&page_size=100&name=&use_regex=false&pagination=true

 * Operating system on which you are running your browser, and its version
Windows 10

 * Errors reported in the JavaScript console (if any)
Status Code: 400 

https://docs.spring.io/spring-security/site/docs/4.2.7.RELEASE/apidocs/org/springframework/security/web/firewall/StrictHttpFirewall.html

**Comment by michaelklishin** [comment]
We will not be replacing %-encoding. It's a standard way of URL path encoding and has been for ages.
Assuming that %-encoding will go away because of even the most popular framework is shortsighted and naive.

Default virtual host name can be [changed to any value](https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example#L186) and at least with the Pivotal BOSH release of RabbitMQ, the default virtual host is deleted at deployment time.

**Comment by michaelklishin** [comment]
Of course it is also possible to change default virtual host name in RabbitMQ 3.6.15 as well. The example can be found [on the 3.6.x branch](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/docs/rabbitmq.config.example#L180).
