### ISSUE TITLE
Is client-side table sorting a good idea?

### ISSUE THREAD

**Issue by kitsirota** [rabbitmq/rabbitmq-management#612]
In deployments with 10k+ objects like queues or connections, table sorting can often take 30+ seconds to return a response.  Although a bit hard to quantify on a live cluster, we do observe a spike in reductions for metrics on the worker serving the request.  Overall CPU/memory utilization does seem to go up when the request is made, but not clear how much of it is specifically attributed to the call.  Its also not clear how much of it is related to the sorting logic.  

1. Is the load generated by sort/pagination actually something we want to optimize?
2. If so, would it make sense to offload the sorting logic for management UI tables (eg queues tab) to the client side using something like https://datatables.net/manual/styling/jqueryui?  

I'd be happy to work on a PR for a POC of this (eg move queues tab to jquery UI datatables) if this makes sense and would fit into the management plugin roadmap.

**Comment by michaelklishin** [comment]
We always welcome reasonable optimizations, including those in the UI.

CPU usage of what host specifically are we talking? See https://github.com/rabbitmq/rabbitmq-management/pull/399 and https://github.com/rabbitmq/rabbitmq-management/issues/417 before you spend any time on it. Sorting and filtering are expensive on the coordinating node (the one that handles HTTP API request)  since results are aggregated from all cluster nodes. Taking "top N" requires merging all result set from each node first.

**Comment by kitsirota** [comment]
Thanks so much for the reference @michaelklishin!  

I was observing (not very scientifically) the host processing the web request spiking load when large queue sort requests were made against it.  I was thinking of updating the UI templates to make unsorted requests (whatever is the default) and offloading all the sorting to the browser.  However after first glance at the tickets you mentioned, I may be going in the wrong direction.   Im going to dig into those tickets first.
