### ISSUE TITLE
A way to control Content-Security-Policy header

### ISSUE THREAD

**Issue by marcopiazzi** [rabbitmq/rabbitmq-management#623]
* RabbitMQ version: 3.7.7
* Erlang version: 20.1  

The RabbitMQ UI Console Management has a Cross-site framing vulnerability: is it possible to set Content-Security-Policy headers?

![image](https://user-images.githubusercontent.com/12832793/47710792-f5cb8a00-dc33-11e8-83d2-56f67e0824bb.png)

**Comment by michaelklishin** [comment]
We would greatly appreciate if vulnerabilities or alleged vulnerabilities were responsibly disclosed to the security address listed on rabbitmq.com in the future instead of public dumping.

There is no way to control arbitrary headers used by the plugin but some headers, e.g. CORS, can be controlled. [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) has to be added. It's a good question what default would be safe to use given the breadth of existing installations in all kinds of environments.

A reverse proxy such as Nginx, HAproxy or Apache can be used to control headers today, with any version.
