### ISSUE TITLE
[HTTP API] create queue of type quorum

### ISSUE THREAD

**Issue by adrpp** [rabbitmq/rabbitmq-management#752]
Hello,

is there a way to specify the type of the queue being created via http api ?
  
* RabbitMQ version: 3.8.1
* Erlang version: 21.3.8.10
* RabbitMQ plugin information via `rabbitmq-plugins list`:
[E*] rabbitmq_management               3.8.1
[E*] rabbitmq_management_agent         3.8.1
[e*] rabbitmq_peer_discovery_common    3.8.1
[E*] rabbitmq_peer_discovery_k8s       3.8.1
[e*] rabbitmq_web_dispatch             3.8.1
* Client library version (for all libraries used): http api included in rabbitmq_management
* Operating system, version, and patch level: Ubuntu 18.04.3 LTS

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * How the HTTP API requests performed can be reproduced with `curl`:
```curl -X PUT -i -u USER:PASS HOST/api/queues/%2F/test```

Creating queue 'test' with command above, creates a queue of type "classic".
Api docs do not mention how to define "queue type", so how to create a queue of type "quorum" ?

https://rawcdn.githack.com/rabbitmq/rabbitmq-management/v3.8.1/priv/www/api/index.html
> /api/queues/vhost/name 
> An individual queue. To PUT a queue, you will need a body looking something like this:           {"auto_delete":false,"durable":true,"arguments":{},"node":"rabbit@smacmullen"}           All keys are optional.
> 

Thanks,
Rgds,
Adrian

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
