### ISSUE TITLE
CORS policy block API 

### ISSUE THREAD

**Issue by alanperius** [rabbitmq/rabbitmq-management#778]
Hi guys,

I'm creating a interface to see some messages from rabbit queues... and trying to use the HTTP API i'm getting this error when I send a request:

`  testPost() {
    fetch('http://localhost:15672/api/queues/test2/alan_queue/get', {
      method: 'post',
      body: JSON.stringify(test),
      headers: {Authorization: 'Basic ' + btoa('test:test')}
    });
  }`

**Access to XMLHttpRequest at 'http://localhost:15672/api/queues/test2/alan_queue/get' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

I tried to add on **rabbitmq.conf** this props:

[{rabbit,
  [ 
    {loopback_users, []},
    {rabbitmq_management, [{listener, [{port, 15672}]}]},
    {rabbitmq_management, [{cors_allow_origins, ["*"]}]}
  ]
}].

but do not worked.
I'm missing something? I need to add this configs on advanced.config?

**If I send an request from postman to the same url, same body works fine...** 

thanks,
Alan

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`rabbitmq.conf` is the file that uses a different config format from what you are trying to use. Relevant doc guides:

 * [Configuration files](https://www.rabbitmq.com/configure.html#configuration-files)
 * [CORS in HTTP API](https://www.rabbitmq.com/management.html#cors)
