### ISSUE TITLE
RabbitMQ - Get Messages -  with thousands 

### ISSUE THREAD

**Issue by alanperius** [rabbitmq/rabbitmq-management#792]
Hello guys, I don't know if is a bug or what. 

Actually we have one Queue that we sent All messages with any kind of error( to track it later if needed).  But now, this queue have over 50k messages. When I try to get All these messages to find someone specific the browser don't show. All messages is moved to **Unacked** and than _stay forever there without any action_(my guess here, if rabbit got any error then this connection should be closed and all message need to back to **ready** state).

When this queue had about 35K all worked fine. But now with more than 40k its not working more.. 

Rabbit do not accept queue with 40k + messages on **Get Message** action?

Thanks,
Alan

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid we cannot suggest much without knowing what "working" means exactly and what various metrics looks like. 40K unacknowledged messages mean that your consumers [do not acknowledge them](https://www.rabbitmq.com/confirms.html) as they should.

A backlog of unacknowledged deliveries is kept in memory so it will cause a higher than usual memory footprint. Again, we cannot suggest anything without metrics and logs but your apps are not doing what they are supposed to do. [Channel prefetch](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch) can be used to limit such backlog of unacknowledged deliveries to, say, 200 or any other desired number.
