### ISSUE TITLE
Consumer utilisation is reported as null by this plugin but not CLI tools

### ISSUE THREAD

**Issue by CrazyMushu** [rabbitmq/rabbitmq-management#798]
* RabbitMQ version 3.8.3
* Erlang version 22.3.1
* RabbitMQ Management plugin version 3.8.3
* OS Ubuntu 16.04

Hello ! I've found the problem in the HTTP API of the RabbitMQ Management plugin.
When accessing  _http://localhost:15672/api/queues/vhost/name_, if there is no load on the queue, the consumer_utilisation parameter is null. 

![a1ab310ed9cbbd9cee9b6dde381534c3](https://user-images.githubusercontent.com/44494231/78996272-ea7ccd80-7b4c-11ea-8f3b-684a360ab996.png)

At the same time, when accessing the same queue through rabbitmqctl, the consumer_utilisation parameter is in the state 1.0

```
$ rabbitmqctl list_queues name messages messages_ready state consumer_utilisation --formatter json | grep -e TestRequestQueue

{"name":"TestRequestQueue","messages":0,"messages_ready":0,"state":"running","consumer_utilisation":1.0}
```

Could you, please, advise what could be the problem in?

**Comment by michaelklishin** [comment]
This plugin relies on periodically emitted stats while CLI tools go "straight to the source".

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
