### ISSUE TITLE
Chat not visible，Brower console error

### ISSUE THREAD

**Issue by shanzhaozhen** [rabbitmq/rabbitmq-management#799]
Hello, my PC cann't see chat，Brower console error `Uncaught TypeError: $.plot is not a function` in charts.js
RabbitMQ version：rabbitmq-management-3.8.3
Running environment：docker 

![image](https://user-images.githubusercontent.com/29800728/79128121-946e8b00-7dd5-11ea-9110-7124dec56b8d.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid I cannot reproduce. If you have previously used management UI in an older version, please clear all browser caches before trying again. That said, the charts library or its dependencies haven't changed in a few years.
