### ISSUE TITLE
Unable to set "undefined" argument value for headers exchange binding

### ISSUE THREAD

**Issue by shark300** [rabbitmq/rabbitmq-management#866]
* RabbitMQ version: 3.8.3
* Erlang version: 21.3.8.15
* RabbitMQ server and client application log files:
> 2020-11-06 16:59:26.191 [error] <0.13675.51> Ranch listener rabbit_web_dispatch_sup_15672, connection process <0.13675.51>, stream 1 had its request process <0.13674.51> exit with reason {nocatch,{error,null_not_allowed}} and stacktrace [{rabbit_misc,type_val,1,[{file,"src/rabbit_misc.erl"},{line,417}]},{rabbit_misc,to_amqp_table_row,2,[{file,"src/rabbit_misc.erl"},{line,404}]},{rabbit_misc,'-to_amqp_table/1-fun-0-',3,[{file,"src/rabbit_misc.erl"},{line,398}]},{maps,fold_1,3,[{file,"maps.erl"},{line,257}]},{rabbit_misc,to_amqp_table,1,[{file,"src/rabbit_misc.erl"},{line,398}]},{rabbit_mgmt_format,format_args,1,[{file,"src/rabbit_mgmt_format.erl"},{line,98}]},{rabbit_mgmt_format,'-format/2-lc$^1/1-1-',2,[{file,"src/rabbit_mgmt_format.erl"},{line,52}]},{rabbit_mgmt_util,props_to_method,2,[{file,"src/rabbit_mgmt_util.erl"},{line,909}]}]
> 2020-11-06 16:59:26.190 [error] <0.13674.51> CRASH REPORT Process <0.13674.51> with 0 neighbours crashed with reason: {error,null_not_allowed} in rabbit_misc:type_val/1 line 417
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue

```bash
curl --location --request POST 'https://rabbitmq-test.okdtest.vodafone.hu/api/bindings/sample-vhost/e/sample.ex/q/sample.q/' \
--header 'Authorization: Basic c2FtcGxlLW1hbjpwYXNzd29yZA==' \
--header 'Content-Type: application/json' \
--data-raw '{"routing_key":"", "arguments":{"type": null}}'`
```
```java
@Bean
public Binding binding(
    HeadersExchange exchange, Queue queue) {
  return BindingBuilder.bind(queue)
      .to(exchange)
      .where("type")
      .exists();
}
```

* RabbitMQ plugin information via `rabbitmq-plugins list`
  * rabbitmq_management
* Client library version (for all libraries used)
  * spring-amqp-2.2.10-RELEASE
  * spring-rabbit-2.2.10-RELEASE
* Operating system, version, and patch level
  * RedHat

When a binding is created by Spring, arguments could be undefined, but it is not possible to configure on UI or by REST.

**Comment by lukebakken** [comment]
Are you certain that this code ...

```
      .where("type")
      .exists();
```

...is correctly represented by this JSON?

```
"arguments":{"type": null}}
```

**Comment by lukebakken** [comment]
Could you please run your Spring code to create the exchange and binding, then export your RabbitMQ definitions to see what JSON is produce (attach it to your response)? Or, provide a *complete* set of code I can clone, compile and run to see how Spring does it. That would speed up diagnosis greatly as it would save me the time of figuring out how to get the Spring code running.

**Comment by shark300** [comment]
Maybe yes, but I can't figure out how to configure it on UI too. If I leave empty, it causes an empty String not "undefined" on UI.

**Comment by lukebakken** [comment]
@shark300 please see [this comment](https://github.com/rabbitmq/rabbitmq-management/issues/866#issuecomment-723174130). Thanks.

**Comment by shark300** [comment]
Yes, sure.

**Comment by michaelklishin** [comment]
```
"arguments":{"type": null}}
```

is not a valid value that we want to support. As of https://github.com/rabbitmq/rabbitmq-management/issues/761, there is a default type for `rabbitmqadmin` because it is extremely common to leave out the arguments field. IIRC the core had a similar change but I cannot find what release that happened in.

We only spend time investigating behaviors that can be reproduced with `3.8.9`. However, `"type": null` is just not a sensible value to use (an omitted type is a different story).

**Comment by michaelklishin** [comment]
OK, this turned out to be a different `arguments` value (a binding one, not the queue one).

These `curl` commands work as expected:

``` shell
curl -u guest:guest --location --request POST http://localhost:15672/api/bindings/%2F/e/he.1/q/cq.1/ --header 'Content-Type: application/json' --data-raw '{"routing_key":"", "arguments":{}}'

curl -u guest:guest --location --request POST http://localhost:15672/api/bindings/%2F/e/he.1/q/cq.1/ --header 'Content-Type: application/json' --data-raw '{"routing_key":"", "arguments":{"type": "blue"}}'
```

This does not create a binding:

``` shell
curl -u guest:guest --location --request POST http://localhost:15672/api/bindings/%2F/e/he.1/q/cq.1/ --header 'Content-Type: application/json' --data-raw '{"routing_key":"", "arguments":{"type": null}}'
```

and the node logs an exception, `{error,null_not_allowed}`.

There is no way to tell a headers exchange match on an absence of a value, the closest option is to match on "one of the values" using the `"x-match" => "any"` argument (as opposed to `"x-match" => "all"`). So this limitation makes sense to me.
The plugin could report validation failure better, e.g. with a `400` response.
